name: agluzhin-ci-cd

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  # Сборка проекта.
  build:
    runs-on: ubuntu-latest
    steps:
    
        # Проверка кода.
      - name: Checkout code
        uses: actions/checkout@v4
        
        # Установка JDK 17-й версии.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

        # Кеширование зависимостей сборщика (maven).
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

        # Сборка проекта сборщиком (maven).
      - name: Build with Maven
        run: mvn clean package -DskipTests

  # Тестирование проекта.
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
        # Проверка кода.
      - name: Checkout code
        uses: actions/checkout@v4

        # Установка JDK 17-й версии.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

        # Запуск unit-тестов проекта.
      - name: Run tests
        run: mvn test

  # Деплой проекта.
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:

        # Проверка кода.
      - name: Checkout code
        uses: actions/checkout@v4

        # Деплой на удаленный сервер по SSH.
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd myapp/agluzhin_app
            docker stop agluzhin-container 2>/dev/null || echo "Container not running"
            docker rm agluzhin-container 2>/dev/null || echo "Container already removed"
            docker rmi agluzhin-app:latest 2>/dev/null || echo "Image not found"

            git pull origin main
            docker build -t agluzhin-app:latest .
            
            docker run -d --name agluzhin-container -p 8080:8080 agluzhin-app:latest
